docs: Expand storage docs
k8s-at-home/docs pull request #49
Opened 2021-11-10 19:04 UTC by bjw-s

Signed-off-by: Bᴇʀɴᴅ Sᴄʜᴏʀɢᴇʀs <me@bjw-s.dev>

**Description of the change**

These are the Storage docs that go along with the changes in https://github.com/k8s-at-home/library-charts/pull/108

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

2021-11-10 20:06 UTC, onedr0p requested changes

2021-11-10 20:06 UTC, onedr0p commented on docs/our-container-images/permissions.md
> +  * This is typically much faster than `Always`
This indentation isn't working correctly, it requires 4 spaces for sub items, see https://github.com/k8s-at-home/docs/commit/867fa6b12ffd41fcc818326bdd4ff7294fa3e5e5

2021-11-10 21:01 UTC, bjw-s commented on docs/our-container-images/permissions.md
> +  * This is typically much faster than `Always`
Ah, I did that to fix the linter complaining. Will try to find a way to silence the linter without this indentation change

2021-11-15 17:59 UTC, bjw-s commented on docs/our-container-images/permissions.md
> +  * This is typically much faster than `Always`
Fixed in latest commit :)

2021-11-16 00:45 UTC, onedr0p approved these changes

2021-11-16 14:06 UTC, merged